"""Initial migration

Revision ID: ed5de416e00a
Revises: 
Create Date: 2026-08-27 14:21:27.630372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed5de416e00a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BMS_SUBSYSTEM',
    sa.Column('id_subsystem', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_subsystem')
    )
    op.create_table('RISK_CLASSIFICATION',
    sa.Column('id_classification', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=True),
    sa.Column('score_min', sa.Integer(), nullable=True),
    sa.Column('score_max', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_classification')
    )
    op.create_table('RISK_FACTOR',
    sa.Column('id_factor', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_factor')
    )
    op.create_table('DEVICE_TYPE',
    sa.Column('id_device_type', sa.String(length=36), nullable=False),
    sa.Column('primary_data_collected', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('id_subsystem', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['id_subsystem'], ['BMS_SUBSYSTEM.id_subsystem'], ),
    sa.PrimaryKeyConstraint('id_device_type')
    )
    op.create_table('DEVICE',
    sa.Column('id_device', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id_device_type', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['id_device_type'], ['DEVICE_TYPE.id_device_type'], ),
    sa.PrimaryKeyConstraint('id_device')
    )
    op.create_table('DEVICE_DATA_SAMPLE',
    sa.Column('id_sample', sa.String(length=36), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('data_value', sa.String(length=50), nullable=True),
    sa.Column('id_device', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['id_device'], ['DEVICE.id_device'], ),
    sa.PrimaryKeyConstraint('id_sample')
    )
    op.create_table('DEVICE_FACTOR_SCORE',
    sa.Column('id_device_factore_score', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('rated_at', sa.DateTime(), nullable=True),
    sa.Column('id_device', sa.String(length=36), nullable=False),
    sa.Column('id_factor', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['id_device'], ['DEVICE.id_device'], ),
    sa.ForeignKeyConstraint(['id_factor'], ['RISK_FACTOR.id_factor'], ),
    sa.PrimaryKeyConstraint('id_device_factore_score')
    )
    op.create_table('RISK_SCORE_HISTORY',
    sa.Column('id_history', sa.String(length=36), nullable=False),
    sa.Column('raw_score', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('normalized_score', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.Column('id_device', sa.String(length=36), nullable=False),
    sa.Column('id_classification', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['id_classification'], ['RISK_CLASSIFICATION.id_classification'], ),
    sa.ForeignKeyConstraint(['id_device'], ['DEVICE.id_device'], ),
    sa.PrimaryKeyConstraint('id_history')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RISK_SCORE_HISTORY')
    op.drop_table('DEVICE_FACTOR_SCORE')
    op.drop_table('DEVICE_DATA_SAMPLE')
    op.drop_table('DEVICE')
    op.drop_table('DEVICE_TYPE')
    op.drop_table('RISK_FACTOR')
    op.drop_table('RISK_CLASSIFICATION')
    op.drop_table('BMS_SUBSYSTEM')
    # ### end Alembic commands ###
